name: Update Index

on: [push]

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate index
        uses: docker://aoswalt/notoriety
        with:
          args: --root-dir /github/workspace

      - name: Commit index
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update index
