name: Update Index

on: [push]

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate index
        uses: docker://aoswalt/notoriety
        with:
          entrypoint: /bin/sh
          args: -c "cd /github/workspace && notoriety"

      - name: Commit index
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update index
